#!/usr/bin/env bash
source /opt/nexusplus/lib/common.sh
source /opt/nexusplus/lib/users.sh
change_expiry(){ header 'MUDAR DATA'; read -r -p 'Usuário: ' u; id "$u" &>/dev/null||{ warn 'Não encontrado';pause;return;}; read -r -p 'Nova data AAAA-MM-DD: ' d; date -d "$d" >/dev/null 2>&1||{ warn 'Data inválida';pause;return;}; chage -E "$d" "$u"; set_kv "$EXPIRY" "$u" "$d 23:59:59";ok 'Data alterada';pause; }
user_report(){ header 'RELATÓRIO DE USUÁRIOS'; printf '%-18s %-8s %-20s %-8s\n' USUARIO LIMITE EXPIRA ONLINE; while IFS=: read -r u _ uid _; do ((uid>=1000&&uid<60000))||continue; printf '%-18s %-8s %-20s %-8s\n' "$u" "$(get_kv "$LIMITS" "$u" 1)" "$(get_kv "$EXPIRY" "$u" '-')" "$(pgrep -u "$u" sshd 2>/dev/null|wc -l)"; done </etc/passwd; pause; }
speedtest_run(){ header 'SPEEDTEST'; command -v speedtest-cli >/dev/null||apt-get install -y speedtest-cli; speedtest-cli; pause; }
banner_manage(){ header 'BANNER SSH'; local f=/etc/issue.net; ${EDITOR:-nano} "$f"; grep -q '^Banner ' /etc/ssh/sshd_config.d/99-nexusplus.conf || echo "Banner $f" >>/etc/ssh/sshd_config.d/99-nexusplus.conf; sshd -t && (systemctl restart ssh 2>/dev/null||systemctl restart sshd); pause; }
traffic_monitor(){ header 'TRÁFEGO'; command -v nload >/dev/null||apt-get install -y nload; nload; }
swap_manage(){ header 'MEMÓRIA VIRTUAL'; free -h; echo; echo '1) Criar/alterar swapfile'; echo '2) Remover swapfile'; echo '0) Voltar'; read -r -p 'Opção: ' o; case $o in 1)read -r -p 'Tamanho em GB [2]: ' g;g=${g:-2};[[ $g =~ ^[1-9][0-9]*$ ]]||{ warn Inválido;pause;return;};swapoff /swapfile 2>/dev/null||true;rm -f /swapfile;fallocate -l "${g}G" /swapfile||dd if=/dev/zero of=/swapfile bs=1M count=$((g*1024));chmod 600 /swapfile;mkswap /swapfile;swapon /swapfile;grep -q '^/swapfile ' /etc/fstab||echo '/swapfile none swap sw 0 0' >>/etc/fstab;ok 'Swap configurada';;2)swapoff /swapfile 2>/dev/null||true;sed -i '\#^/swapfile #d' /etc/fstab;rm -f /swapfile;ok 'Swap removida';;esac;pause; }
info_vps(){ header 'INFO VPS'; echo "SO: $(. /etc/os-release;echo "$PRETTY_NAME")"; echo "Kernel: $(uname -r)"; echo "Arquitetura: $(uname -m)"; echo "CPU: $(nproc) núcleo(s)"; free -h; df -h /; echo "IP público: $(curl -4fsS --max-time 3 https://api.ipify.org 2>/dev/null||echo indisponível)"; echo; ss -lntup | head -40; pause; }
limiter_status(){ header 'LIMITADOR'; systemctl status nexusplus-limiter.timer --no-pager || true; echo; /opt/nexusplus/bin/nexus-limiter --report 2>/dev/null || true; pause; }
health_menu(){ header 'SAÚDE / DIAGNÓSTICO'; /opt/nexusplus/bin/nexus-health all; pause; }
